version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./iaphpbotman/public:/var/www/html/public"
        # Routing via Traefik; Please remove comments to allow direct access
        # ports:
        #     - "8200:80"
        command: /bin/sh -c "nginx -g 'daemon off;'"
        restart: unless-stopped
        labels:
            - "traefik.frontend.rule=Host: ia004.chatopswg.xyz"
        logging:
            options:
                max-size: 10m
                max-file: '3'
    php:
        image: nanoninja/php-fpm:7.1
        restart: unless-stopped
        volumes:
            # - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./iaphpbotman:/var/www/html"
        # Routing via Traefik; Please remove comments to allow direct access
        # ports:
        #     - "3200:3000"
        labels:
            - "traefik.enable=false"
        logging:
            options:
                max-size: 10m
                max-file: '3'
