version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./iaphpbotman/public:/var/www/html/public"
        ports:
            - "8200:80"
        command: /bin/sh -c "nginx -g 'daemon off;'"
        restart: always
        labels:
            - "traefik.frontend.rule=Host: ia004.chatopswg.xyz"
    php:
        image: nanoninja/php-fpm:7.1
        restart: always
        volumes:
            # - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./iaphpbotman:/var/www/html"
        ports:
            - "3000:3000"